### ISSUE TITLE
Tutorial/Docs

### ISSUE THREAD

**Issue by MystPi** [hayleigh-dot-dev/gleam-nibble#6]
Nibble looks like a phenomenal project and I'm very keen to use it, but the lack of a tutorial/documentation makes it very difficult to know where to begin. I don't think a long, in-depth tutorial is required; just one that covers enough of the basics so one could start a parser with confidence.

**Comment by coder0107git** [comment]
Also, every thing in the pages section of the docs is empty (except the Lexer Modes and README pages).
